version: '3'

services:

  pgsql:
    build:
      context: ../../
      dockerfile: ./deployments/lab14/pgsql/Dockerfile
    container_name: calendar-pgsql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local

  rabbitmq:
    image: rabbitmq:3-management
    hostname: calendar-rabbit
    container_name: calendar-rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
#    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpass
#   ports:
#      - 15672:15672
#      - 5672:5672
    expose:
       - 5672
    networks:
      - local

  calendar:
    build:
      context: ../../
      dockerfile: ./deployments/lab14/calendar/Dockerfile
    container_name: calendar-app
    depends_on:
       pgsql:
          condition: service_healthy
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "8800:8800"
    networks:
      - local
    environment:
      - CALENDAR_DB_USER=calendar
      - CALENDAR_DB_PASS=pass


  scheduler:
    build:
      context: ../../
      dockerfile: ./deployments/lab14/scheduler/Dockerfile
    container_name: calendar-scheduler
    depends_on:
      pgsql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always
    tty: true
    stdin_open: true
    networks:
      - local
    environment:
      - CALENDAR_DB_USER=calendar
      - CALENDAR_DB_PASS=pass
      - RABBIT_USER=rmuser
      - RABBIT_PASS=rmpass

  sender:
    build:
      context: ../../
      dockerfile: ./deployments/lab14/sender/Dockerfile
    container_name: calendar-sender
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    tty: true
    stdin_open: true
    networks:
      - local
    environment:
      - RABBIT_USER=rmuser
      - RABBIT_PASS=rmpass

  generator:
    build:
      context: ../../
      dockerfile: ./deployments/lab14/generator/Dockerfile
    container_name: calendar-generator
    depends_on:
      pgsql:
        condition: service_healthy
    restart: always
    tty: true
    stdin_open: true
    networks:
      - local
    environment:
      - CALENDAR_DB_USER=calendar
      - CALENDAR_DB_PASS=pass


networks:
  local: