storage:
  #type memory / pgsql / mysql
  type: memory

bindings:
  port: 8800
  address: 0.0.0.0 # 0.0.0.0 - all interfaces / ip address for binding

logger:
  loglevel: INFO
  # if logfile empty, or it cannot be created, service logs to the console.
  logfile:

service:
  #if logfile is empty or destination is not accessible service does logging into the current directory
  logfile: /tmp/calendar01.log


#if storage type=memory following line are omitted

#due security reasons, service gets username and password for database from env settings
env:
  dbuser: CALENDAR_DB_USER
  dbpass: CALENDAR_DB_PASS

db:
  port: 3306
  address: localhost
  db: calendar
  maxopenconns: 5 #10 default
  maxidleconns: 5 #10 default
  maxidletime: 5m # 15m default value if omitted. f.e: 1h5m10s, 10m...
